### ISSUE TITLE
Can atmospheric correction be done with this reflectance values ?

### ISSUE THREAD

**Issue by Khumayun** [atedstone/micasense_calibration#2]
This `micasense_calibration` does not include atmospheric calibration, so how can I implement it ?
Probably SMAC algorithm does not fit images taken from quad/plane height..

I would really appreciate anybody who can help.

**Comment by atedstone** [comment]
We only fly our UAV platforms at around 30 m above the surface, so atmospheric calibration is not relevant. Sorry that I and this set of scripts cannot be of help.
